// <auto-generated />
namespace Pidu_proov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class puha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(puha));
        
        string IMigrationMetadata.Id
        {
            get { return "202601150926157_puha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
